### ISSUE TITLE
Filter modal doesn't include all operators

### ISSUE THREAD

**Issue by ryanv94** [newrelic/nr1-event-stream#28]
## Description

Event Stream Users have a need to use operators such as `NOT LIKE`. While `LIKE` exists, `NOT LIKE` does not. 

## Steps to Reproduce
Open the Filter Modal & click the drop down menu for Operator & notice a lack of `NOT LIKE`

![image](https://user-images.githubusercontent.com/37779995/84491458-7ec5f680-ac9c-11ea-814b-67f06dd61977.png)

## Expected Behaviour

We expect a `NOT LIKE` operator

## Relevant Logs / Console output

N/A

## Your Environment

N/A

## Additional context

This has been reported by a Nerdpack User here: https://discuss.newrelic.com/t/event-stream-nerdpack/83285/5

**Comment by Kav91** [comment]
Fixed in 1.3.1, pending app catalog release.
