### ISSUE TITLE
App not visible in New Relic ONE when locally served or published

### ISSUE THREAD

**Issue by xrismck** [newrelic/nr1-event-stream#9]
I've tried to use this Nerdpack with local hosting (development) and have tried to publish/deploy/subscribe to NewRelic ONE on a DEV channel. 

**My experience with this NerdPack**
_I've been unsuccessful serving locally and to  New Relic ONE._

**My experiences with all NerdPacks I've tried:**

**SUCCESSES**
>nr1-cloud-optimize
>nr1-container-explorer
>nr1-customer-journey
>nr1-datalyzer
>nr1-groundskeeper
>nr1-neon

**FAILURES**
>nr1-event-stream                
>nr1-browser-analyzer
>nr1-top

**OBSERVATIONS/CAVEATS/EXCUSE-MES**

- The issues I've experienced may be self-inflicted. I'm just getting started with NerdPacks.
- The issues I've come across with NerdPack usage seem to be consistent with a minority of the NerdPacks.
- I've tried to be consistent about raising issues with each NerdPack repo, but repeatedly providing the same level of detail is tedious. I may have made some mistakes with respect to posting details (nr1 nerdpack:info --verbose). 
- **My comments are me are to be helpful and constructive**

---
**Walkthrough: Development, served localhost**
---
**Clone**
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-event-stream.git 
``` 
Cloning repository...
Removing remote origin...
Installing dependencies...
Re-generating UUID...
Committing new UUID...

 ✔   The Nerdpack has been successfully cloned!

To start this project run:
 ⁎   cd nr1-event-stream
 ⁎   nr1 nerdpack:serve
```
**Comments**
- Clone process already created a new UUID.
-- Why use nr1 nerdpack:uuid -gf ?
- Instructions are confusing
-- clone output:  nr1 nerdpack:serve
-- README:  npm install; npm start
- Are these equivalent?  _nr1 nerdpack:serve_ AND _npm install; npm start_
----------------------------------------------------------------------
**Check Info**
nr1 nerdpack:info --verbose
```
init version: @oclif/command@1.5.19 argv: [ '--verbose', [length]: 1 ]
Fetching info from registry...
Request: POST https://artifact-registry.service.newrelic.com/graphql
Data: 'query {\n                package(uuid: ' +
  '"73a596df-226f-480c-812e-3d95c5ecc07c") {\n               ' +
  '     uuid\n                    accountId\n                 ' +
  '   publications {\n                        createdAt\n     ' +
  '                   createdByUser\n                        ' +
  'version\n                    }\n                }\n         ' +
  '       packageDeployments(uuid: ' +
  '"73a596df-226f-480c-812e-3d95c5ecc07c") {\n               ' +
  '     channel\n                    deployedPublication {\n  ' +
  '                      version\n                    }\n     ' +
  '           }\n            }'
Headers: {
  'API-Key': '<my api key>',
  'Content-Type': 'application/graphql'
}

Registry: Present
Id: 73a596df-226f-480c-812e-3d95c5ecc07c
Region: us
Account ID: 1847652
Local version: 0.1.8 [NOT IN THE REGISTRY]

Version   Date           Deployed to channel
```
**Comments**
- Output confusing
-- Registry: Present
-- Then:  (NOT IN REGISTRY)
----------------------------------------------------------------------
**Initialize local server**
cd nr1-event-stream
nr1 nerdpack:serve
```
Nerdpack:

  package.json:
    ✔ name nr1-event-stream
    ✔ id 73a596df-226f-480c-812e-3d95c5ecc07c

Artifacts:

  Nerdlets:
    ✔ event-stream nerdlets/event-stream/nr1.json

🛠  Built artifact files for:
 ⁎   73a596df-226f-480c-812e-3d95c5ecc07c--event-stream built ✔
 ⁎   73a596df-226f-480c-812e-3d95c5ecc07c--styles built ✔

 ✔   Nerdpack built successfully!
 ★   Starting as orchestrator...

 ✔   Server ready! Test it at: https://one.newrelic.com/?nerdpacks=local
 ↩   Server will reload automatically if you modify any file!
```
**Comments**
- App not displayed via:  https://one.newrelic.com/?nerdpacks=local
- No connection error
----------------------------------------------------------------------
**Reinstall app using git clone output instructions**
sudo rm -Rf nr1-event-stream
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-event-stream.git
cd nr1-event-stream
nr1 nerdpack:uuid -gf
```
Generated id is 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e
```

**Install**
npm install
```
audited 680 packages in 1.204s
found 0 vulnerabilities
```
**Start**
npm start
```
> nr1-event-stream@0.1.8 start /Users/NEX66CO/projects/docker/nr1-event-stream
> nr1 nerdpack:serve

Nerdpack:

  package.json:
    ✔ name nr1-event-stream
    ✔ id 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e

Artifacts:

  Nerdlets:
    ✔ event-stream nerdlets/event-stream/nr1.json

🛠  Built artifact files for:
 ⁎   4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e--event-stream built ✔
 ⁎   4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e--styles built ✔

 ✔   Nerdpack built successfully!
 ★   Starting as orchestrator...

 ✔   Server ready! Test it at: https://one.newrelic.com/?nerdpacks=local
 ↩   Server will reload automatically if you modify any file!
```
**Comments**
- App not displayed via:  https://one.newrelic.com/?nerdpacks=local
- No connection error

---
**Walkthrough: Published to NewRelic ONE**
---
**Publish**
nr1 nerdpack:publish -f
```
Nerdpack:

  package.json:
    ✔ name nr1-event-stream
    ✔ id 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e

Artifacts:

  Nerdlets:
    ✔ event-stream nerdlets/event-stream/nr1.json

Building nerdpack nr1-event-stream (4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e)...

🛠  Built artifact files for:
 ⁎   4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e--event-stream built ✔
 ⁎   4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e--styles built ✔

 ✔   Nerdpack built successfully!

Deploying Nerdpack nr1-event-stream (4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e)
 ✔   Published successfully!
```
**Deploy**
nr1 nerdpack:deploy --channel=DEV
```
Deployed 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e version 0.1.8 to the DEV channel.
```
**Subscribe**
nr1 nerdpack:subscribe --channel=DEV
```
Subscribed account 1847652 to the nerdpack 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e on the DEV channel
```
**Check Info**
nr1 nerdpack:info --verbose
```
init version: @oclif/command@1.5.19 argv: [ '--verbose', [length]: 1 ]
Fetching info from registry...
Request: POST https://artifact-registry.service.newrelic.com/graphql
Data: 'query {\n                package(uuid: ' +
  '"4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e") {\n               ' +
  '     uuid\n                    accountId\n                 ' +
  '   publications {\n                        createdAt\n     ' +
  '                   createdByUser\n                        ' +
  'version\n                    }\n                }\n         ' +
  '       packageDeployments(uuid: ' +
  '"4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e") {\n               ' +
  '     channel\n                    deployedPublication {\n  ' +
  '                      version\n                    }\n     ' +
  '           }\n            }'
Headers: {
  'API-Key': 'L2DQZGJMCYYIIL3B9DI9ABW2DH7S7UZY',
  'Content-Type': 'application/graphql'
}

Registry: Present
Id: 4e4dd2aa-d30b-4b4e-b960-bf32bd3f436e
Region: us
Account ID: 1847652
Local version: 0.1.8

Version   Date           Deployed to channel
0.1.8     2 minutes ago  DEV
```
**Comments**
- App not displayed via:  https://one.newrelic.com

---
**Conclusion**
--- 
- Let me know if there are other tests/details that'll help the advancement of this project
- I welcome an invite to the Slack channel for this NerdPack

**Comment by tangollama** [comment]
This, again, is another nerdpack that does not surface a launcher. You need to navigate to it via the entity explorer. Choose a service. Then you’ll see this app show up in the left hand nav.

**Comment by tangollama** [comment]
@xrismck see the reply above. I believe your nerdpack is functioning and that you’re expecting it to show up somewhere it does not.

**Comment by tangollama** [comment]
That said, I really appreciate how detailed your reports are. Any chance you’re interested in getting involved to any of these projects as a contributor?

**Comment by Kav91** [comment]
@xrismck have you tried @tangollama's suggestion? 
This nerdpack and the failure cases you've mentioned above are nerdpacks that only function/appear when viewing particular entities as they are in context of that entity itself and do not require a launcher.

**Comment by Kav91** [comment]
Closing since no response. 
Further help can also be found in our discussion forums if required.
